version: '3'

services:
  app1:
    build: ./app
    ports:
      - "8000:8000"
    environment:
      - IS_MASTER=1
      - APP_PORT=8000
    networks:
      - app-network
  app2:
    build: ./app
    ports:
      - "8001:8000"
    environment:
      - IS_MASTER=0
      - APP_PORT=8001
    networks:
      - app-network
  app3:
    build: ./app
    ports:
      - "8002:8000"
    environment:
      - IS_MASTER=0
      - APP_PORT=8002
    networks:
      - app-network
  fake_input:
    build: ./fake_input
    networks:
      - app-network

networks:
  app-network:
